name: CitySim
main: dev.citysim.CitySimPlugin
version: 0.5.3
api-version: 1.21
authors: [ 'botshashka' ]
description: SimCity-like city stats for villagers (Paper)
commands:
  city:
    description: Manage cities and view stats
    usage: /city help
    aliases: [cities]
permissions:
  citysim.admin:
    default: op
  citysim.view:
    default: true
softdepend: [PlaceholderAPI]
