# CitySim plugin configuration
# You can tweak update intervals and happiness weights later.
updates:
  stats_interval_ticks: 100     # ~5 seconds
  bossbar_interval_ticks: 40    # ~2 seconds

happiness_weights:
  nature_max_points: 10
  pollution_max_penalty: 15
  housing_max_points: 10
  water_max_points: 5
  beauty_max_points: 5
  light_max_points: 10
  employment_max_points: 15
  safety_max_points: 2.5
  overcrowding_max_penalty: 10


employment:
  mode: profession_only  # profession_only | profession_and_workstation | workstation_proximity
  workstation_radius: 16
  workstation_y_radius: 8


titles:
  enabled: true
  cooldown_ticks: 80
  messages:
    bright:
      - "Bright, well-lit streets"
      - "Lanterns chase away the night"
      - "No shadows left for trouble to hide"
    dark:
      - "Dark streets feel unsafe"
      - "Too many corners lost to darkness"
      - "Citizens whisper about unlit alleys"
    employment_good:
      - "High employment keeps spirits up"
      - "Every villager has meaningful work"
      - "Jobs are plentiful and morale is high"
    employment_bad:
      - "Rampant unemployment angers citizens"
      - "Idle hands are stirring frustration"
      - "Too many villagers are out of work"
    safety_good:
      - "Guards make it feel safe"
      - "Patrolling defenders keep danger at bay"
      - "Citizens salute their protectors"
    safety_bad:
      - "Citizens feel unprotected"
      - "Where are the defenders when night falls?"
      - "Villagers fear monsters without guardians"
    crowding_good:
      - "Comfortable spacing"
      - "Plenty of room to breathe"
      - "Homes feel cozy without feeling cramped"
    crowding_bad:
      - "Overcrowded — expand the city"
      - "Cramped housing sparks complaints"
      - "Citizens are stacked on top of each other"
    nature_good:
      - "Green, lively parks"
      - "Trees and flowers lift everyone's mood"
      - "Nature weaves through every street"
    nature_bad:
      - "Concrete jungle — residents miss nature"
      - "Citizens crave trees and gardens"
      - "A barren city leaves spirits low"
    pollution_good:
      - "Clean air and skies"
      - "Fresh breezes sweep the city"
      - "Clear skies keep lungs happy"
    pollution_bad:
      - "Polluted air is choking the city"
      - "Smog clouds every sunrise"
      - "Sooty air keeps citizens indoors"
    housing_good:
      - "Everyone has a place to sleep"
      - "Every villager rests easy at night"
      - "Comfortable housing keeps morale high"
    housing_bad:
      - "Homelessness is spreading"
      - "Villagers curl up on floors without shelter"
      - "Citizens are desperate for housing"
    water_good:
      - "Soothing water nearby"
      - "Fountains and canals cool the air"
      - "Water features calm worried minds"
    water_bad:
      - "Parched city — add water"
      - "Residents thirst for fountains"
      - "Dry plazas leave tempers hot"
    beauty_good:
      - "Charming decorations"
      - "Artful touches delight citizens"
      - "Beauty blooms on every corner"
    beauty_bad:
      - "Bleak, uninspired streets"
      - "Drab blocks sap citizen pride"
      - "The city longs for artistic flair"
    default_good:
      - "Citizens are content"
      - "Life is peaceful in the city"
      - "Villagers seem pleased overall"
    default_bad:
      - "Citizens feel uneasy"
      - "Whispers of discontent spread"
      - "Morale is slipping across the city"
